core/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.urls import path, include
from core.views import SignUpView
from .forms import LoginForm
from . import views

app_name = "core"

urlpatterns = [
    path('', views.ListaAvaliacoesView.as_view(), name='lista_avaliacoes'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/signup/", SignUpView.as_view(), name="signup"),
    path('login/', LoginView.as_view(
            template_name='login.html',
            authentication_form=LoginForm
        ),
        name='login'
    ),
    path('logout/', LogoutView.as_view(
        next_page=reverse_lazy("core:lista_avaliacoes")),
        name='logout'
    ),
    path('fazer-avaliacao/', views.FazerAvaliacaoView.as_view(), name='fazer_avaliacao'),
]

sistema_avaliacao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Minhas URLs
    path('', include('core.urls', 'core'), name='core'),
]

core/models.py
from django.db import models

class Avaliacao(models.Model):
    """Uma avaliação no site."""
    nome = models.CharField(max_length=100)
    nota = models.IntegerField()
    comentario = models.TextField()
    criado_em = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Avaliação"
        verbose_name_plural = "Avaliações"

    def __str__(self):
        return f"{self.nome} - Nota: {self.nota}"

core/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import Avaliacao

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(label="Nome", max_length=30, required=False)
    last_name  = forms.CharField(label="Sobrenome", max_length=30, required=False)
    email      = forms.EmailField(label="E-mail", required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Remove help_texts longos e adiciona classes/placeholders
        field_cfg = {
            "username":  {"ph": "Seu nome de usuário"},
            "first_name":{"ph": "Seu nome"},
            "last_name": {"ph": "Seu sobrenome"},
            "email":     {"ph": "seu@email.com", "type": "email", "autocomplete": "email"},
            "password1": {"ph": "Crie uma senha", "type": "password", "autocomplete": "new-password"},
            "password2": {"ph": "Confirme a senha", "type": "password", "autocomplete": "new-password"},
        }
        for name, f in self.fields.items():
            f.help_text = ""
            f.widget.attrs.update({
                "class": "form-control",
                "placeholder": field_cfg.get(name, {}).get("ph", ""),
                "autocomplete": field_cfg.get(name, {}).get("autocomplete", "off"),
                "type": field_cfg.get(name, {}).get("type", f.widget.input_type if hasattr(f.widget, "input_type") else "text")
            })

    def clean_email(self):
        email = self.cleaned_data["email"].lower().strip()
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError("Já existe um usuário com este e-mail.")
        return email
    

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Digite seu usuário'
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Digite sua senha'
        })


class AvaliacaoForm(forms.ModelForm):

    class Meta:
        model = Avaliacao
        fields = ['nome', 'nota', 'comentario']
        widgets = {
            'nome': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Digite seu nome',
            }),
            
            'nota': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Digite uma nota',
                'min': 0,
                'max': 10,
            }),

            'comentario': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Faça um comentário',
            }),
        }

core/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.views.generic import ListView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .forms import AvaliacaoForm, CustomUserCreationForm
from .models import Avaliacao

class ViewProtegida(LoginRequiredMixin):
    login_url = reverse_lazy("core:login")
    redirect_field_name = "next"


class ListaAvaliacoesView(ListView):
    model = Avaliacao
    template_name = "lista-avaliacoes.html"
    context_object_name = "avaliacoes"
    paginate_by = 10
    ordering = "-criado_em"


class FazerAvaliacaoView(ViewProtegida, CreateView):

    model = Avaliacao
    form_class = AvaliacaoForm
    template_name = "fazer-avaliacao.html"
    success_url = reverse_lazy("core:lista_avaliacoes")


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "signup.html"
    success_url = reverse_lazy("core:lista_avaliacoes")  # ajuste se quiser

    # loga o usuário após cadastrar
    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        return response

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=devide-width, initial-scale=1.0">
    <title>Sistema de Avaliação</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.1/src/regular/style.css"
    />
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}?v=1.0.0">
    {% block styles %}{% endblock styles %}
</head>

<body>
    <header class="container">
        <h1>Sistema de Avaliação</h1>
        <nav>
            <ul>
                <li><a href="{% url 'core:lista_avaliacoes' %}">Lista de Avaliações</a></li>
                <li><a href="{% url 'core:fazer_avaliacao' %}">Fazer Avaliação</a></li>
            </ul>

            {% if request.user.is_authenticated %}
            <form action="{% url 'core:logout' %}?next={% url 'core:lista_avaliacoes' %}"
                    method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="user-link" style="background:none;border:0;cursor:pointer;">
                <i class="ph ph-user"></i>
                <span>Olá, {{ request.user }}. Sair</span>
                </button>
            </form>
            {% else %}
            <a href="{% url 'core:login' %}" class="user-link">
                <i class="ph ph-user"></i>
                <span>Entrar / Cadastrar-se</span>
            </a>
            {% endif %}
        </nav>
    </header>

    <main class="container">
        {% block content %}{% endblock content %}
    </main>

    <footer class="container">
        <p>&copy; Luiz R. Dererita, Todos os Direitos Reservados - 2025</p>
    </footer>
</body>
</html>

core/templates/fazer-avaliacao.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'core/css/fazer-avaliacao.css' %}?v=1.0.0">
{% endblock styles %}

{% block content %}
<div class="form-wrapper">
    <h2>Fazer nova avaliação</h2>
    <form class="evaluation-form" method="POST">
        {% csrf_token %}

        {{ form.nome.errors }}
        {{ form.nome }}

        {{ form.nota.errors }}
        {{ form.nota }}

        {{ form.comentario.errors }}
        {{ form.comentario }}
        
        <button type="submit">Enviar</button>
    </form>
</div>
{% endblock content %}

core/templates/lista-avaliacoes.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static  'core/css/lista-avaliacoes.css' %}?v=1.0.0">
{% endblock styles %}

{% block content %}
<div class="evaluations-list">
  {% for avaliacao in avaliacoes %}
  <div class="evaluation-card">
    <div class="evaluation-info">
      <div class="info-wrapper">
        <span class="evaluation-name">{{ avaliacao.nome }}</span>
        <span class="evaluation-note">{{ avaliacao.nota }}/10</span>
      </div>
      <span class="evaluation-date">{{ avaliacao.criado_em }}</span>
    </div>

    <span class="evaluation-comment">"{{ avaliacao.comentario }}"</span>
  </div>
  {% empty %}
  <p>Nenhuma avaliação ainda foi feita.</p>
  {% endfor %}
</div>
{% endblock content %}

core/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'core/css/fazer-avaliacao.css' %}?v=1.0.0">
{% endblock styles %}

{% block content %}
<div class="form-wrapper">
    <h2>Fazer login</h2>
    <form class="evaluation-form" method="POST">
        {% csrf_token %}
        
        {{ form.username.errors }}
        {{ form.username }}

        {{ form.password.errors }}
        {{ form.password }}

        <button type="submit">Entrar</button>
    </form>
    <p class="auth-alt">Ainda não tem uma conta? <a href="{% url 'core:signup' %}">Criar</a></p>
</div>
{% endblock content %}

core/templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'core/css/fazer-avaliacao.css' %}?v=1.0.0">
{% endblock styles %}

{% block content %}
<div class="form-wrapper">
    <h2>Criar conta</h2>
    <form class="evaluation-form" method="POST">
        {% csrf_token %}
        
        {{ form.username.errors }}
        {{ form.username }}

        {{ form.email.errors }}
        {{ form.email }}

        {{ form.first_name.errors }}
        {{ form.first_name }}

        {{ form.last_name.errors }}
        {{ form.last_name }}

        {{ form.password1.errors }}
        {{ form.password1 }}

        {{ form.password2.errors }}
        {{ form.password2 }}

        <button type="submit">Entrar</button>
        <p class="auth-alt">Já tem conta? <a href="{% url 'core:login' %}">Entre</a></p>
    </form>
    <a href="{% url 'core:register' %}">Eu ainda não tenho uma conta</a>
</div>
{% endblock content %}

core/templates/signup.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'core/css/fazer-avaliacao.css' %}?v=1.0.0">
{% endblock styles %}

{% block content %}
<div class="form-wrapper">
    <h2>Criar conta</h2>
    <form class="evaluation-form" method="POST">
        {% csrf_token %}
        
        {{ form.username.errors }}
        {{ form.username }}

        {{ form.email.errors }}
        {{ form.email }}

        {{ form.first_name.errors }}
        {{ form.first_name }}

        {{ form.last_name.errors }}
        {{ form.last_name }}

        {{ form.password1.errors }}
        {{ form.password1 }}

        {{ form.password2.errors }}
        {{ form.password2 }}

        <button type="submit">Criar</button>
    </form>
    <p class="auth-alt">Já tem conta? <a href="{% url 'core:login' %}">Entre</a></p>
</div>
{% endblock content %}